pipeline:
  identifier: Build_backstage_plugins_1703593276189
  name: Build backstage-plugins
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: gitconnector
        repoName: backstage-plugins
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest
                  name: npm_test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest1
                  name: npm_test
                  spec:
                    command: npm run lint
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Run_4
                  identifier: Run_4
                  spec:
                    shell: Sh
                    command: echo "hello world"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
